// Code generated by stanc v2.39.0
#include <stan/model/model_header.hpp>
namespace reported_frequency_bad_normal_example_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 45> locations_array__ =
  {" (found before start of program)",
  " (in 'reported_frequency_bad_normal_example.stan', line 29, column 4 to column 12)",
  " (in 'reported_frequency_bad_normal_example.stan', line 30, column 4 to column 24)",
  " (in 'reported_frequency_bad_normal_example.stan', line 43, column 4 to column 71)",
  " (in 'reported_frequency_bad_normal_example.stan', line 44, column 4 to column 26)",
  " (in 'reported_frequency_bad_normal_example.stan', line 46, column 8 to column 57)",
  " (in 'reported_frequency_bad_normal_example.stan', line 45, column 19 to line 47, column 5)",
  " (in 'reported_frequency_bad_normal_example.stan', line 45, column 4 to line 47, column 5)",
  " (in 'reported_frequency_bad_normal_example.stan', line 34, column 4 to column 23)",
  " (in 'reported_frequency_bad_normal_example.stan', line 35, column 4 to column 34)",
  " (in 'reported_frequency_bad_normal_example.stan', line 39, column 8 to column 32)",
  " (in 'reported_frequency_bad_normal_example.stan', line 38, column 21 to line 40, column 5)",
  " (in 'reported_frequency_bad_normal_example.stan', line 38, column 4 to line 40, column 5)",
  " (in 'reported_frequency_bad_normal_example.stan', line 2, column 4 to column 10)",
  " (in 'reported_frequency_bad_normal_example.stan', line 3, column 4 to column 15)",
  " (in 'reported_frequency_bad_normal_example.stan', line 4, column 4 to column 16)",
  " (in 'reported_frequency_bad_normal_example.stan', line 5, column 4 to column 16)",
  " (in 'reported_frequency_bad_normal_example.stan', line 6, column 20 to column 21)",
  " (in 'reported_frequency_bad_normal_example.stan', line 6, column 23 to column 29)",
  " (in 'reported_frequency_bad_normal_example.stan', line 6, column 4 to column 33)",
  " (in 'reported_frequency_bad_normal_example.stan', line 7, column 23 to column 24)",
  " (in 'reported_frequency_bad_normal_example.stan', line 7, column 4 to column 28)",
  " (in 'reported_frequency_bad_normal_example.stan', line 8, column 23 to column 24)",
  " (in 'reported_frequency_bad_normal_example.stan', line 8, column 4 to column 37)",
  " (in 'reported_frequency_bad_normal_example.stan', line 9, column 10 to column 11)",
  " (in 'reported_frequency_bad_normal_example.stan', line 9, column 4 to column 49)",
  " (in 'reported_frequency_bad_normal_example.stan', line 10, column 10 to column 11)",
  " (in 'reported_frequency_bad_normal_example.stan', line 10, column 4 to column 49)",
  " (in 'reported_frequency_bad_normal_example.stan', line 12, column 4 to column 15)",
  " (in 'reported_frequency_bad_normal_example.stan', line 13, column 10 to column 16)",
  " (in 'reported_frequency_bad_normal_example.stan', line 13, column 4 to column 51)",
  " (in 'reported_frequency_bad_normal_example.stan', line 14, column 23 to column 29)",
  " (in 'reported_frequency_bad_normal_example.stan', line 14, column 4 to column 33)",
  " (in 'reported_frequency_bad_normal_example.stan', line 16, column 4 to column 37)",
  " (in 'reported_frequency_bad_normal_example.stan', line 19, column 4 to column 24)",
  " (in 'reported_frequency_bad_normal_example.stan', line 21, column 10 to column 11)",
  " (in 'reported_frequency_bad_normal_example.stan', line 21, column 4 to column 51)",
  " (in 'reported_frequency_bad_normal_example.stan', line 22, column 26 to column 32)",
  " (in 'reported_frequency_bad_normal_example.stan', line 22, column 4 to column 42)",
  " (in 'reported_frequency_bad_normal_example.stan', line 24, column 8 to column 32)",
  " (in 'reported_frequency_bad_normal_example.stan', line 25, column 8 to column 47)",
  " (in 'reported_frequency_bad_normal_example.stan', line 23, column 24 to line 26, column 5)",
  " (in 'reported_frequency_bad_normal_example.stan', line 23, column 4 to line 26, column 5)",
  " (in 'reported_frequency_bad_normal_example.stan', line 43, column 10 to column 11)",
  " (in 'reported_frequency_bad_normal_example.stan', line 44, column 11 to column 12)"};
class reported_frequency_bad_normal_example_model final : public model_base_crtp<reported_frequency_bad_normal_example_model> {
 private:
  int N;
  int E_cols;
  int K_class;
  int K_state;
  Eigen::Matrix<double,-1,-1> E_data__;
  Eigen::Matrix<double,-1,1> t_data__;
  Eigen::Matrix<double,-1,1> policy_age_data__;
  std::vector<int> g_class;
  std::vector<int> g_state;
  int C_rows;
  std::vector<int> idx_policy;
  Eigen::Matrix<double,-1,1> R_data__;
  int prior_only;
  double epsilon;
  std::vector<int> C_R;
  Eigen::Matrix<double,-1,1> R_trunc_data__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> E{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> t{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> policy_age{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> R{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> R_trunc{nullptr, 0};
 public:
  ~reported_frequency_bad_normal_example_model() {}
  reported_frequency_bad_normal_example_model(stan::io::var_context&
                                              context__, unsigned int
                                              random_seed__ = 0,
                                              std::ostream*
                                              pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "reported_frequency_bad_normal_example_model_namespace::reported_frequency_bad_normal_example_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 13;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 13;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 14;
      context__.validate_dims("data initialization", "E_cols", "int",
        std::vector<size_t>{});
      E_cols = std::numeric_limits<int>::min();
      current_statement__ = 14;
      E_cols = context__.vals_i("E_cols")[(1 - 1)];
      current_statement__ = 15;
      context__.validate_dims("data initialization", "K_class", "int",
        std::vector<size_t>{});
      K_class = std::numeric_limits<int>::min();
      current_statement__ = 15;
      K_class = context__.vals_i("K_class")[(1 - 1)];
      current_statement__ = 16;
      context__.validate_dims("data initialization", "K_state", "int",
        std::vector<size_t>{});
      K_state = std::numeric_limits<int>::min();
      current_statement__ = 16;
      K_state = context__.vals_i("K_state")[(1 - 1)];
      current_statement__ = 17;
      stan::math::validate_non_negative_index("E", "N", N);
      current_statement__ = 18;
      stan::math::validate_non_negative_index("E", "E_cols", E_cols);
      current_statement__ = 19;
      context__.validate_dims("data initialization", "E", "double",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>(E_cols)});
      E_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, E_cols,
                   std::numeric_limits<double>::quiet_NaN());
      new (&E) Eigen::Map<Eigen::Matrix<double,-1,-1>>(E_data__.data(), N,
        E_cols);
      {
        std::vector<local_scalar_t__> E_flat__;
        current_statement__ = 19;
        E_flat__ = context__.vals_r("E");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= E_cols; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(E, E_flat__[(pos__ - 1)],
              "assigning variable E", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 19;
      stan::math::check_greater_or_equal(function__, "E", E, 0);
      current_statement__ = 20;
      stan::math::validate_non_negative_index("t", "N", N);
      current_statement__ = 21;
      context__.validate_dims("data initialization", "t", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      t_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&t) Eigen::Map<Eigen::Matrix<double,-1,1>>(t_data__.data(), N);
      {
        std::vector<local_scalar_t__> t_flat__;
        current_statement__ = 21;
        t_flat__ = context__.vals_r("t");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(t, t_flat__[(pos__ - 1)],
            "assigning variable t", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      stan::math::check_greater_or_equal(function__, "t", t, 1e-5);
      current_statement__ = 22;
      stan::math::validate_non_negative_index("policy_age", "N", N);
      current_statement__ = 23;
      context__.validate_dims("data initialization", "policy_age", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      policy_age_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                            std::numeric_limits<double>::quiet_NaN());
      new (&policy_age)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(policy_age_data__.data(), N);
      {
        std::vector<local_scalar_t__> policy_age_flat__;
        current_statement__ = 23;
        policy_age_flat__ = context__.vals_r("policy_age");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(policy_age, policy_age_flat__[(pos__ - 1)],
            "assigning variable policy_age", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "policy_age",
        policy_age, 1e-5);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("g_class", "N", N);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "g_class", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      g_class = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 25;
      g_class = context__.vals_i("g_class");
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "g_class", g_class, 1);
      current_statement__ = 25;
      stan::math::check_less_or_equal(function__, "g_class", g_class, K_class);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("g_state", "N", N);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "g_state", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      g_state = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 27;
      g_state = context__.vals_i("g_state");
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "g_state", g_state, 1);
      current_statement__ = 27;
      stan::math::check_less_or_equal(function__, "g_state", g_state, K_state);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "C_rows", "int",
        std::vector<size_t>{});
      C_rows = std::numeric_limits<int>::min();
      current_statement__ = 28;
      C_rows = context__.vals_i("C_rows")[(1 - 1)];
      current_statement__ = 29;
      stan::math::validate_non_negative_index("idx_policy", "C_rows", C_rows);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "idx_policy", "int",
        std::vector<size_t>{static_cast<size_t>(C_rows)});
      idx_policy = std::vector<int>(C_rows, std::numeric_limits<int>::min());
      current_statement__ = 30;
      idx_policy = context__.vals_i("idx_policy");
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "idx_policy",
        idx_policy, 1);
      current_statement__ = 30;
      stan::math::check_less_or_equal(function__, "idx_policy", idx_policy, N);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("R", "C_rows", C_rows);
      current_statement__ = 32;
      context__.validate_dims("data initialization", "R", "double",
        std::vector<size_t>{static_cast<size_t>(C_rows)});
      R_data__ = Eigen::Matrix<double,-1,1>::Constant(C_rows,
                   std::numeric_limits<double>::quiet_NaN());
      new (&R) Eigen::Map<Eigen::Matrix<double,-1,1>>(R_data__.data(),
        C_rows);
      {
        std::vector<local_scalar_t__> R_flat__;
        current_statement__ = 32;
        R_flat__ = context__.vals_r("R");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= C_rows; ++sym1__) {
          stan::model::assign(R, R_flat__[(pos__ - 1)],
            "assigning variable R", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::check_greater_or_equal(function__, "R", R, 1e-5);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "prior_only", "int",
        std::vector<size_t>{});
      prior_only = std::numeric_limits<int>::min();
      current_statement__ = 33;
      prior_only = context__.vals_i("prior_only")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "prior_only",
        prior_only, 0);
      current_statement__ = 33;
      stan::math::check_less_or_equal(function__, "prior_only", prior_only, 1);
      current_statement__ = 34;
      epsilon = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 34;
      epsilon = 1e-5;
      current_statement__ = 35;
      stan::math::validate_non_negative_index("C_R", "N", N);
      current_statement__ = 36;
      C_R = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 36;
      stan::model::assign(C_R, stan::math::zeros_int_array(N),
        "assigning variable C_R");
      current_statement__ = 37;
      stan::math::validate_non_negative_index("R_trunc", "C_rows", C_rows);
      current_statement__ = 38;
      R_trunc_data__ = Eigen::Matrix<double,-1,1>::Constant(C_rows,
                         std::numeric_limits<double>::quiet_NaN());
      new (&R_trunc)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(R_trunc_data__.data(), C_rows);
      current_statement__ = 42;
      for (int c = 1; c <= C_rows; ++c) {
        current_statement__ = 39;
        stan::model::assign(C_R,
          (stan::model::rvalue(C_R, "C_R",
             stan::model::index_uni(
               stan::model::rvalue(idx_policy, "idx_policy",
                 stan::model::index_uni(c)))) + 1), "assigning variable C_R",
          stan::model::index_uni(
            stan::model::rvalue(idx_policy, "idx_policy",
              stan::model::index_uni(c))));
        current_statement__ = 40;
        stan::model::assign(R_trunc,
          stan::model::rvalue(policy_age, "policy_age",
            stan::model::index_uni(
              stan::model::rvalue(idx_policy, "idx_policy",
                stan::model::index_uni(c)))), "assigning variable R_trunc",
          stan::model::index_uni(c));
      }
      current_statement__ = 36;
      stan::math::check_greater_or_equal(function__, "C_R", C_R, 0);
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "R_trunc", R_trunc,
        epsilon);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("C_R_post_pred", "N", N);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("C_R_log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1;
  }
  inline std::string model_name() const final {
    return "reported_frequency_bad_normal_example_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.39.0",
             "stancflags = --filename-in-msg=reported_frequency_bad_normal_example.stan"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "reported_frequency_bad_normal_example_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto mu = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      {
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu,
                         static_cast<double>(0), static_cast<double>(10)));
        current_statement__ = 9;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma, (1 /
                         10.0)));
        current_statement__ = 12;
        if (stan::math::logical_negation(prior_only)) {
          current_statement__ = 10;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::math::promote_scalar<double>(C_R), mu, sigma));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "reported_frequency_bad_normal_example_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto mu = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      {
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu,
                         static_cast<double>(0), static_cast<double>(10)));
        current_statement__ = 9;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma, (1 /
                         10.0)));
        current_statement__ = 12;
        if (stan::math::logical_negation(prior_only)) {
          current_statement__ = 10;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::math::promote_scalar<double>(C_R), mu, sigma));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "reported_frequency_bad_normal_example_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto mu = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      out__.write(mu);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      std::vector<double> C_R_post_pred =
        std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      stan::model::assign(C_R_post_pred,
        stan::math::normal_rng(stan::math::rep_vector(mu, N), sigma,
          base_rng__), "assigning variable C_R_post_pred");
      Eigen::Matrix<double,-1,1> C_R_log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 5;
        stan::model::assign(C_R_log_lik,
          stan::math::normal_lpdf<false>(
            static_cast<double>(
              stan::model::rvalue(C_R, "C_R", stan::model::index_uni(n))),
            mu, sigma), "assigning variable C_R_log_lik",
          stan::model::index_uni(n));
      }
      out__.write(C_R_post_pred);
      out__.write(C_R_log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.read<local_scalar_t__>();
      out__.write(mu);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = context__.vals_r("mu")[(1 - 1)];
      out__.write(mu);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu", "sigma"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"C_R_post_pred", "C_R_log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "C_R_post_pred" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "C_R_log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "C_R_post_pred" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "C_R_log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"C_R_post_pred\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"C_R_log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"C_R_post_pred\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"C_R_log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1;
    const size_t num_transformed = emit_transformed_parameters * (0U);
    const size_t num_gen_quantities = emit_generated_quantities * (N + N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1;
    const size_t num_transformed = emit_transformed_parameters * (0U);
    const size_t num_gen_quantities = emit_generated_quantities * (N + N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = reported_frequency_bad_normal_example_model_namespace::reported_frequency_bad_normal_example_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return reported_frequency_bad_normal_example_model_namespace::profiles__;
}
#endif